services:
  api:
    container_name: lure_api_srvr
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command: gunicorn --bind 0.0.0.0:5000 --workers 5 app:application
    env_file:
      - ./.env
    ports:
      - "60123:5000"
    networks:
      - lure-net
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./api:/api:Z
    environment:
      - PYTHONUNBUFFERED=1

  mysql:
    container_name: lure_mysql_srvr
    image: mysql:lts
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 30s
    env_file:
      - ./.env
    ports:
      - "60234:${MYSQL_PORT}"
    networks:
      - lure-net
    volumes:
      - mysql-data:/var/lib/mysql:Z

  redis:
    container_name: lure_redis_srvr
    image: redis:7.4-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
    ports:
      - "60345:6379"
    networks:
      - lure-net
    volumes:
      - ./db/redis:/data


volumes:
  mysql-data:
  redis-data:

networks:
  lure-net:
    driver: bridge
