"""asda

Revision ID: 26d1296fe8d7
Revises: 
Create Date: 2025-01-30 13:54:30.377923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26d1296fe8d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'contact_types', ['contact_type_id'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
