"""fdgf

Revision ID: 4b23bad0b39e
Revises: 
Create Date: 2025-06-11 20:11:04.499668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b23bad0b39e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'addresses', ['shipping_address_id'], ['id'])

    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
