"""K

Revision ID: 5673dd8de7b0
Revises: ef87ac0a8f2f
Create Date: 2025-06-01 22:09:24.157006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5673dd8de7b0'
down_revision = 'ef87ac0a8f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'addresses', ['shipping_address_id'], ['id'])

    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipping_address_id')

    # ### end Alembic commands ###
