"""asd

Revision ID: 5a2cb621ada0
Revises: 
Create Date: 2025-05-12 21:14:19.404095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2cb621ada0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('accessed_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['contact_value'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrapings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('accessed_at')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
