"""mi

Revision ID: 6cd6dfede23e
Revises: 73d93034947b
Create Date: 2025-04-29 19:42:32.322631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd6dfede23e'
down_revision = '73d93034947b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shipping_status', ['shipping_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shipping_status_id')

    # ### end Alembic commands ###
