"""asd

Revision ID: 8c77f21f08ca
Revises: 6cd6dfede23e
Create Date: 2025-04-29 20:37:44.681000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c77f21f08ca'
down_revision = '6cd6dfede23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('estimated_delivery_date')

    with op.batch_alter_table('shipping_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.Date(), nullable=True))
        batch_op.drop_index('name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipping_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('tracking_number')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
