"""asd

Revision ID: 8e9fab5ca360
Revises: 
Create Date: 2025-04-13 22:32:12.501729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e9fab5ca360'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('observation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observation', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', mysql.VARCHAR(length=30), nullable=False))

    # ### end Alembic commands ###
