"""asd

Revision ID: feb2af662af1
Revises: 680d98c5d5e6
Create Date: 2025-04-30 19:50:58.363147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'feb2af662af1'
down_revision = '680d98c5d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('purchase_history_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('shipping_address_id')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint('purchases_ibfk_2', type_='foreignkey')
        batch_op.drop_column('shipping_address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('purchases_ibfk_2', 'addresses', ['shipping_address_id'], ['id'])

    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('purchase_history_ibfk_2', 'addresses', ['shipping_address_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
