"""Testing

Revision ID: 0af2171933ec
Revises: 
Create Date: 2024-09-25 09:27:56.338501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0af2171933ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.drop_column('size_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('products_ibfk_1', 'sizes', ['size_id'], ['id'])

    # ### end Alembic commands ###
